# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9e951617aaa0908a9f431ad9df700b444e634655ea3b17a7ed70598c442bc7f07a46460aba89627976567b0f5cca32acd08d0619d790d23e7ec4e3569fcd5f39

test:
  secret_key_base: 5cc31bd1e8d42863e00fc87bfa811ee71da95dc56dc89775629a3872117b9807db908364ac1e8e54c35afd735d8b65cfec138aaf783bc2c4f57016fb186ac164

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
